version: 0.0
os: linux
files:
  - source: MVCWebApplication/bin/Release/net5.0/publish
    destination: /var/www/
  - source: deployscripts/website.service
    destination: /etc/systemd/system
hooks:
  ApplicationStop:
    - location: deployscripts/application_stop.sh
      timeout: 300
  BeforeInstall:
    - location: deployscripts/before-install.sh
      timeout: 300
  ApplicationStart:
    - location: deployscripts/application_start.sh
      timeout: 300
