version: 0.0
os: linux
files:
  - source: app
    destination: /var/www
  - source: deployscripts/website.service
    destination: /etc/systemd/system
hooks:
  ApplicationStop:
    - location: deployscripts/application_stop.sh
      timeout: 10
  BeforeInstall:
    - location: deployscripts/before-install.sh
      timeout: 10
  ApplicationStart:
    - location: deployscripts/application_start.sh
      timeout: 10
