version: 0.0
os: windows
files:
  - source: MVCWebApplication/bin/net5.0/publish
    destination: C:\webApps\MVCWebApplication
  - source: deployscripts/deletewebsite.ps1
    destination: c:\temp
  - source: deployscripts/installwebsite.ps1
    destination: c:\temp
  - source: deployscripts/deletewebsite.bat
    destination: c:\temp
  - source: deployscripts/installwebsite.bat
    destination: c:\temp
hooks:
  ApplicationStop:
  #    - location: deployscripts/deletewebsite.bat
  #      timeout: 300
  ApplicationStart:
  #   - location: deployscripts/installwebsite.bat
  #     timeout: 300
