version: 0.0
os: windows
files:
  - source: MVCWebApplication/bin/Release/net5.0/publish
    destination: C:\webApps\MVCWebApplication
hooks:
  ApplicationStop:
  #    - location: deployscripts/application_stop.bat
  #      timeout: 300
  BeforeInstall:
  #    - location: deployscripts/before-install.bat
  #      timeout: 300
  ApplicationStart:
  #   - location: deployscripts/application_start.bat
  #     timeout: 300
